<div class="footer-wrapper">
    <div class="footer-links">
        <div class="col-xs-6 col-sm-4">
            <h1></h1>
            <div class="footer-links__list">
                <a href="{{store url=" "}}"></a>
                <a href="{{store url=" "}}"></a>
                <a href="{{store url=" "}}"></a>
                <a href="{{store url=" "}}"></a>
                <a href="{{store url=" "}}"></a>
            </div>
        </div>
        <div class="footer-links__list">
            <div class="col-xs-6 col-sm-4">
                <h1></h1>
                <div class="footer-links__list">
                    <a href="{{store url=" "}}"></a>
                    <a href="{{store url=" "}}"></a>
                    <a href="{{store url=" "}}"></a>
                    <a href="{{store url=" "}}"></a>
                    <a href="{{store url=" "}}"></a>
                </div>
            </div>
        </div>
        <div class="footer-links__list">
            <div class="col-xs-6 col-sm-4">
                    <h1></h1>
                    <div class="footer-links__list">
                        <a href="{{store url=" "}}"></a>
                        <a href="{{store url=" "}}"></a>
                        <a href="{{store url=" "}}"></a>
                        <a href="{{store url=" "}}"></a>
                        <a href="{{store url=" "}}"></a>
                    </div>
                </div>
        </div>
        <div class="footer-links__social">
            <div class="col-xs-6 col-sm-4">
                <h1></h1>
                <div>
                    <a href=""></a>
                    <a href=""></a>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-image">
        <img src="" alt="">
    </div>
</div>