<div class="footer-wrapper">
    <div class="footer-links">
        <div class="footer-links__list">
            <a href=""></a>
            <a href=""></a>
            <a href=""></a>
            <a href=""></a>
            <a href=""></a>
        </div>
        <div class="footer-links__list"></div>
        <div class="footer-links__list"></div>
        <div class="footer-links__social"></div>
    </div>
    <div class="footer-image">
        <img src="" alt="">
    </div>
</div>