<div class="footer-wrapper">
    <div class="footer-links">
        <div class="footer-links__block">
            <div class="col-xs-6 col-sm-4 column-list">
                <h1>MI CUENTA</h1>
                <div class="footer-links__list">
                    <a href="{{store url=" "}}">Nuevos usuarios</a>
                    <a href="{{store url=" "}}">Mi compra</a>
                    <a href="{{store url=" "}}">Mis lista de deseos</a>
                    <a href="{{store url=" "}}">Mis pedidos</a>
                    <a href="{{store url=" "}}"></a>
                </div>
            </div>
        </div>
        <div class="footer-links__block">
            <div class="col-xs-6 col-sm-4 column-list">
                <h1>SERVICIOS</h1>
                <div class="footer-links__list">
                    <a href="{{store url=" "}}">Descargas</a>
                    <a href="{{store url=" "}}">Noticias</a>
                    <a href="{{store url=" "}}">Eventos</a>
                    <a href="{{store url=" "}}">Blog</a>
                    <a href="{{store url=" "}}">Contacto</a>
                </div>
            </div>
        </div>
        <div class="footer-links__block">
            <div class="col-xs-6 col-sm-4 column-list">
                    <h1>INFORMACIÓN</h1>
                    <div class="footer-links__list">
                        <a href="{{store url=" "}}">Aviso legal</a>
                        <a href="{{store url=" "}}">Condiciones</a>
                        <a href="{{store url=" "}}">Cookies</a>
                        <a href="{{store url=" "}}">Privacidad</a>
                        <a href="{{store url=" "}}">Devoluciones</a>
                    </div>
                </div>
        </div>
        <div class="footer-links__social">
            <div class="col-xs-6 col-sm-4 column-list">
                <h1>REDES SOCIALES</h1>
                <div>
                    <a href=""></a>
                    <a href=""></a>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-image">
        <img src="" alt="">
    </div>
</div>