

<!-- <div  class="field choice taxvat">
                <input type="checkbox" onchange="javascript:showContent()" name="activate_nif" title="<?= $block->escapeHtmlAttr(__('¿Quieres Factura?')) ?>" value="1" id="activate_nif" class="checkbox">
                <label for="activate_nif" class="label"><span><?= $block->escapeHtml(__('¿Quieres Factura?')) ?></span></label>
</div> -->

<!-- <div data-mage-init='{"test": {"message": "Bienvenido a GiuntiEos!"}}'>
    Content
</div>

<script type="text/javascript">
 require(['jquery', 'domReady!'], function($){
 var $bt = $('#shipping-new-address-form');
//  console.log(JSON.stringify($bt)); 
    alert(JSON.stringify($bt));
 
 return false;
     });

</script> -->

